### ISSUE TITLE
CRC error on unzipping

### ISSUE THREAD

**Issue by bin101** [withgallantry/RetropieFE#1]
Hi,

I keep getting crc errors when I unzip the RC-1 zip. I started the download on my windows and linux machine. Both with the same result.

You could provide a file hash with the next/corrected version?,

bin101

**Comment by withgallantry** [comment]
I would recommend trying to burn the zip directly without extracting first using 
https://www.balena.io/etcher/

**Comment by carroarmato0** [comment]
@bin101 I downloaded it and unzipped it just fine yesterday.

**Comment by KonnorJ** [comment]
I downloaded and flashed this multiple times on my unit just fine too.

**Comment by hakahakahakahaka** [comment]
I sadly got the same problem. Any chance to get the .img unzipped?

**Comment by withgallantry** [comment]
Are you attempting to unzip the image? @hakahakahakahaka

**Comment by carroarmato0** [comment]
I think it would remove a lot of doubt if the repository contained the hash of the image so everyone can confirm that the downloaded image is exactly the same as the one uploaded.

**Comment by withgallantry** [comment]
I think it's because it's being unzipped in isolation when it was designed
to be burnt straight to an SD card without unzipping first.
I will definitely add a hash to future releases, good suggestion.

**Comment by carroarmato0** [comment]
@withgallantry oh interesting, I've always unzipped first and then copied the image through dd (on Linux).
@hakahakahakahaka what system are you running? Windows, Mac, Linux? And what tool are you using to unzip? That might give some more clues to work with.

**Comment by hakahakahakahaka** [comment]
I used Win10 and Balena Etcher. I downloaded the image several times and now it worked, it was maybe the 10th try or so.

**Comment by mosse-r** [comment]
I had the same issue on both linux and macOS with Balena Etcher 

md5sum: 256dd2d62881254dd2f4138be2d91322

Has anyone got a hash of a good image?

**Comment by mosse-r** [comment]
I actually tried the sd after it had failed in etcher, it looks like it had already flashed the image at that point and the sd boots ok.

**Comment by withgallantry** [comment]
The first boot will take a couple of minutes, a few people have assumed it's not worked due to this.
I'm working on a new image but so far when I zip it, people are receiving the same issues so I'm working on that. As soon as I get it working I'll update this issue.

**Comment by KonnorJ** [comment]
@withgallantry This can be closed with the new image
