### ISSUE TITLE
Wifi icon always shows red cross

### ISSUE THREAD

**Issue by bin101** [withgallantry/RetropieFE#2]
If I enable Wifi via the overlay menu (select button), the wifi symbol is always shown with a red cross even If I am connected to a network.

**Comment by withgallantry** [comment]
It will show a red cross if not connected, did you use a wpa_supplicant file or configure it through the Retropie menu? I should make it clearer though as it's not good having the same state for not connected as disabled.

**Comment by bin101** [comment]
I used the wpa_supplicant in the boot partition and I am connected to my wifi.
